// ═══════════════════════════════════════════════════════════════════════════════
// Template: SystemApiAdapter.java.tpl
// Module: mod-code-017-persistence-systemapi
// ═══════════════════════════════════════════════════════════════════════════════
// Output: {{basePackage}}/adapter/out/systemapi/{{Entity}}SystemApiAdapter.java
// Purpose: Adapter implementing repository port via System API calls
// ═══════════════════════════════════════════════════════════════════════════════
// REQUIRED VARIABLES: {{Entity}} {{basePackage}} {{entity}}
// ═══════════════════════════════════════════════════════════════════════════════
// NOTE: This template generates the adapter WITHOUT resilience patterns.
//       Resilience (circuit-breaker, retry, timeout) is added in Phase 3
//       by cross-cutting modules (mod-001, mod-002, mod-003) using flow-transform.
// ═══════════════════════════════════════════════════════════════════════════════

package {{basePackage}}.adapter.out.systemapi;

import {{basePackage}}.adapter.out.systemapi.client.{{Entity}}SystemApiClient;
import {{basePackage}}.adapter.out.systemapi.dto.{{Entity}}Dto;
import {{basePackage}}.adapter.out.systemapi.mapper.{{Entity}}SystemApiMapper;
import {{basePackage}}.domain.model.{{Entity}};
import {{basePackage}}.domain.repository.{{Entity}}Repository;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Optional;

/**
 * System API adapter implementing {{Entity}}Repository port.
 * Delegates persistence to external System API.
 * 
 * Generated by: mod-017-persistence-systemapi
 * ERI Reference: eri-code-012-persistence-patterns-java-spring
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class {{Entity}}SystemApiAdapter implements {{Entity}}Repository {
    
    private final {{Entity}}SystemApiClient client;
    private final {{Entity}}SystemApiMapper mapper;
    
    @Override
    public Optional<{{Entity}}> findById(String id) {
        log.debug("Fetching {{entity}} with id: {}", id);
        {{Entity}}Dto dto = client.getById(id);
        return Optional.ofNullable(mapper.toDomain(dto));
    }
    
    @Override
    public List<{{Entity}}> findAll() {
        log.debug("Fetching all {{entity}}s");
        List<{{Entity}}Dto> dtos = client.getAll();
        return dtos.stream()
            .map(mapper::toDomain)
            .toList();
    }
    
    @Override
    public {{Entity}} save({{Entity}} entity) {
        log.debug("Saving {{entity}}: {}", entity.getId());
        {{Entity}}Dto dto = mapper.toDto(entity);
        {{Entity}}Dto saved = client.save(dto);
        return mapper.toDomain(saved);
    }
    
    @Override
    public void deleteById(String id) {
        log.debug("Deleting {{entity}} with id: {}", id);
        client.deleteById(id);
    }
}
