// Template: SystemApiAdapterTest.java.tpl
// Output: {{basePackagePath}}/adapter/out/systemapi/{{Entity}}SystemApiAdapterTest.java
// Purpose: Unit test for System API adapter

package {{basePackage}}.adapter.out.systemapi;

import {{basePackage}}.adapter.out.systemapi.client.{{Entity}}SystemApiClient;
import {{basePackage}}.adapter.out.systemapi.dto.{{Entity}}SystemApiRequest;
import {{basePackage}}.adapter.out.systemapi.dto.{{Entity}}SystemApiResponse;
import {{basePackage}}.adapter.out.systemapi.mapper.{{Entity}}SystemApiMapper;
import {{basePackage}}.domain.model.{{Entity}};
import {{basePackage}}.domain.model.{{Entity}}Id;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.*;

/**
 * Unit tests for {{Entity}}SystemApiAdapter.
 * 
 * Tests adapter logic with mocked client and mapper.
 * Resilience behavior (circuit breaker, retry) tested separately
 * with integration tests.
 * 
 * Generated by: mod-017-persistence-systemapi
 * ERI Reference: eri-code-012-persistence-patterns-java-spring
 */
@ExtendWith(MockitoExtension.class)
class {{Entity}}SystemApiAdapterTest {
    
    private static final {{Entity}}Id EXISTING_ID = {{Entity}}Id.of(UUID.fromString("a1b2c3d4-e5f6-7890-abcd-ef1234567890"));
    private static final {{Entity}}Id NON_EXISTING_ID = {{Entity}}Id.of(UUID.fromString("00000000-0000-0000-0000-000000000000"));
    private static final String MAINFRAME_ID = "A1B2C3D4";
    
    @Mock
    private {{Entity}}SystemApiClient client;
    
    @Mock
    private {{Entity}}SystemApiMapper mapper;
    
    private {{Entity}}SystemApiAdapter adapter;
    
    @BeforeEach
    void setUp() {
        adapter = new {{Entity}}SystemApiAdapter(client, mapper);
    }
    
    @Test
    void findById_WhenExists_ReturnsMappedEntity() {
        // Given
        {{Entity}}SystemApiResponse dto = {{Entity}}SystemApiResponse.builder().id(MAINFRAME_ID).build();
        {{Entity}} entity = mock({{Entity}}.class);
        
        when(mapper.toMainframeId(EXISTING_ID)).thenReturn(MAINFRAME_ID);
        when(client.getById(MAINFRAME_ID)).thenReturn(dto);
        when(mapper.toDomain(dto)).thenReturn(entity);
        
        // When
        Optional<{{Entity}}> result = adapter.findById(EXISTING_ID);
        
        // Then
        assertThat(result).isPresent();
        verify(client).getById(MAINFRAME_ID);
        verify(mapper).toDomain(dto);
    }
    
    @Test
    void findById_WhenNotExists_ReturnsEmpty() {
        // Given
        when(mapper.toMainframeId(NON_EXISTING_ID)).thenReturn("00000000");
        when(client.getById("00000000")).thenReturn(null);
        when(mapper.toDomain(null)).thenReturn(null);
        
        // When
        Optional<{{Entity}}> result = adapter.findById(NON_EXISTING_ID);
        
        // Then
        assertThat(result).isEmpty();
    }
    
    @Test
    void findAll_ReturnsMappedEntities() {
        // Given
        {{Entity}}SystemApiResponse dto1 = {{Entity}}SystemApiResponse.builder().id("ID1").build();
        {{Entity}}SystemApiResponse dto2 = {{Entity}}SystemApiResponse.builder().id("ID2").build();
        {{Entity}} entity1 = mock({{Entity}}.class);
        {{Entity}} entity2 = mock({{Entity}}.class);
        
        when(client.getAll()).thenReturn(List.of(dto1, dto2));
        when(mapper.toDomain(dto1)).thenReturn(entity1);
        when(mapper.toDomain(dto2)).thenReturn(entity2);
        
        // When
        List<{{Entity}}> result = adapter.findAll();
        
        // Then
        assertThat(result).hasSize(2);
    }
    
    @Test
    void save_ReturnsMappedSavedEntity() {
        // Given
        {{Entity}} entity = mock({{Entity}}.class);
        {{Entity}}SystemApiRequest request = {{Entity}}SystemApiRequest.builder().id(MAINFRAME_ID).build();
        {{Entity}}SystemApiResponse savedDto = {{Entity}}SystemApiResponse.builder().id(MAINFRAME_ID).build();
        {{Entity}} savedEntity = mock({{Entity}}.class);
        
        when(mapper.toRequest(entity)).thenReturn(request);
        when(client.save(request)).thenReturn(savedDto);
        when(mapper.toDomain(savedDto)).thenReturn(savedEntity);
        
        // When
        {{Entity}} result = adapter.save(entity);
        
        // Then
        assertThat(result).isNotNull();
        verify(client).save(request);
    }
    
    @Test
    void deleteById_CallsClient() {
        // Given
        when(mapper.toMainframeId(EXISTING_ID)).thenReturn(MAINFRAME_ID);
        
        // When
        adapter.deleteById(EXISTING_ID);
        
        // Then
        verify(client).deleteById(MAINFRAME_ID);
    }
    
    @Test
    void existsById_WhenExists_ReturnsTrue() {
        // Given
        {{Entity}}SystemApiResponse dto = {{Entity}}SystemApiResponse.builder().id(MAINFRAME_ID).build();
        {{Entity}} entity = mock({{Entity}}.class);
        
        when(mapper.toMainframeId(EXISTING_ID)).thenReturn(MAINFRAME_ID);
        when(client.getById(MAINFRAME_ID)).thenReturn(dto);
        when(mapper.toDomain(dto)).thenReturn(entity);
        
        // When
        boolean result = adapter.existsById(EXISTING_ID);
        
        // Then
        assertThat(result).isTrue();
    }
    
    @Test
    void existsById_WhenNotExists_ReturnsFalse() {
        // Given
        when(mapper.toMainframeId(NON_EXISTING_ID)).thenReturn("00000000");
        when(client.getById("00000000")).thenReturn(null);
        when(mapper.toDomain(null)).thenReturn(null);
        
        // When
        boolean result = adapter.existsById(NON_EXISTING_ID);
        
        // Then
        assertThat(result).isFalse();
    }
}
