// Template: restclient-config.java.tpl
// Output: {{basePackage}}/infrastructure/config/RestClientConfig.java
// Purpose: RestClient bean configuration
// Variant: restclient

package {{basePackage}}.infrastructure.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.client.RestClient;

/**
 * RestClient configuration.
 * 
 * Generated by: mod-018-api-integration-rest-java-spring (restclient variant)
 * ERI Reference: eri-code-013-api-integration-rest-java-spring
 */
@Configuration
public class RestClientConfig {
    
    @Bean
    public RestClient.Builder restClientBuilder() {
        return RestClient.builder();
    }
}
