# ${SERVICE_NAME} — Development Prompt
#
# Generated by: Enablement 2.0 DESIGN Pipeline
# Module: mod-design-003-api-mapping (Step 3.5 — Prompt Assembly)
# Date: ${ANALYSIS_DATE}
# Solution Target: ${SOLUTION_TARGET}
#
# This prompt is the input for the CODE pipeline.
# It replaces manual architect-written prompts.

---

## Service Overview

**Service Name:** ${API_NAME}
**API Tier:** ${API_TIER} API
**API Type:** ${API_TYPE}
**Bounded Context:** ${CONTEXT_NAME} (${CONTEXT_ID})
**Subdomain Type:** ${SUBDOMAIN_TYPE}

### Functional Description

${FUNCTIONAL_DESCRIPTION}

---

## Domain Model

### Aggregate: ${AGGREGATE_NAME}

${AGGREGATE_DESCRIPTION}

**Root Entity:** ${ROOT_ENTITY_NAME}

#### Entities
${ENTITIES_SECTION}

#### Value Objects
${VALUE_OBJECTS_SECTION}

#### Invariants (Business Rules)
${INVARIANTS_SECTION}

---

## API Contract

**Base Path:** ${BASE_PATH}
**Spec File:** ${OPENAPI_SPEC_FILE}

### Operations

${OPERATIONS_TABLE}

### Error Codes

${ERROR_CODES_TABLE}

---

## Integration Context

${INTEGRATION_SECTION}

---

## Constraints

${CONSTRAINTS_SECTION}

---

## Solution Target

**Target:** ${SOLUTION_TARGET}
**Golden Path:** ${GOLDEN_PATH_DESCRIPTION}

### Inherent Capabilities (from Solution Target)
${INHERENT_CAPABILITIES}

### Additional Discovery
The CODE pipeline will discover additional capabilities based on this prompt content.

---

## Files Reference

| Artifact | Location |
|----------|----------|
| API Mapping | api-mapping.yaml |
| OpenAPI Spec | ${OPENAPI_SPEC_FILE} |
| Field Mapping | ${FIELD_MAPPING_FILE} |
| Aggregate Definitions | aggregate-definitions.yaml |
| Bounded Context Map | bounded-context-map.yaml |
| BDD Scenarios | ${FEATURE_FILE} |
